export default {
  input: 'src/index.mjs',
  external: ['path', 'url', 'fs', 'fs/promises', 'import-maps', 'schema-utils'],
  treeshake: false,
  output: {
    file: 'dist/index.cjs',
    format: 'cjs',
    intro: '// This file is auto-generated by Rollup'
  }
};
