// This file is auto-generated by run-fixtures.mjs
import {readFile as readFileAsync} from 'fs/promises';
import {rollup} from 'rollup';
import {importMapsPlugin} from '../src/index.mjs';

describe('TransformImportMaps', () => {
  it('bare-specifier', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/bare-specifier.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('no-transforming', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/no-transforming.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('pathname-specifier', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/pathname-specifier.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('specifier-excluding', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/specifier-excluding.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('specifier-syntax', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/specifier-syntax.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('transforming-report', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/transforming-report.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
  it('url-specifier', async () => {
    let {inputFile, importmapFile, expectedOutputFile, pluginOptions} = (await import('./fixtures/url-specifier.js')).default;
    let bundle = await rollup({
      input: inputFile,
      treeshake: false,
      plugins: [
        importMapsPlugin({
          srcText: await readFileAsync(importmapFile, {encoding: 'utf-8'}),
          ...pluginOptions,
        })
      ],
    });
    let result = await bundle.generate({format: 'es'});
    let output = result.output[0];
    let expectedOutputCode = await readFileAsync(expectedOutputFile, {encoding: 'utf-8'});
    expect(output.code).toEqual(expectedOutputCode);
  });
});
